// Auto-generated by scripts/scrape.mjs — do not edit manually
// Source: https://www.billizone.com/club/cb_main.php?cb_id=aymania
// Scraped at: 2026-09-04T00:49:58.688Z

export const monthlyLabel = "9월";

import type { Member } from './types'

export const memberData: Member[] = [
  {
    nickname: "9샷레이첼",
    avatarColor: "#f472b6",
    monthly: null,
    allTime: null,
  },
  {
    nickname: "9샷마스웨이",
    avatarColor: "#34d399",
    monthly: null,
    allTime: {
      average: 0.388,
      highrun: 7,
      win: 25,
      draw: 0,
      loss: 17,
      winRate: 60,
      ranks: {
        average: null,
        highrun: null,
        winRate: 67,
      },
    },
  },
  {
    nickname: "9샷애호박",
    avatarColor: "#a78bfa",
    monthly: null,
    allTime: {
      average: 0.43,
      highrun: 6,
      win: 10,
      draw: 0,
      loss: 7,
      winRate: 59,
      ranks: {
        average: null,
        highrun: null,
        winRate: 74,
      },
    },
  },
  {
    nickname: "9샷윽고",
    avatarColor: "#60a5fa",
    monthly: null,
    allTime: null,
  },
  {
    nickname: "9샷캐리",
    avatarColor: "#c084fc",
    monthly: null,
    allTime: {
      average: 0.597,
      highrun: 8,
      win: 30,
      draw: 0,
      loss: 22,
      winRate: 58,
      ranks: {
        average: 44,
        highrun: 74,
        winRate: 82,
      },
    },
  },
  {
    nickname: "9샷케인장",
    avatarColor: "#fbbf24",
    monthly: null,
    allTime: {
      average: 0.194,
      highrun: 3,
      win: 21,
      draw: 0,
      loss: 16,
      winRate: 57,
      ranks: {
        average: null,
        highrun: null,
        winRate: 89,
      },
    },
  },
  {
    nickname: "9샷쿤",
    avatarColor: "#2dd4bf",
    monthly: null,
    allTime: null,
  },
  {
    nickname: "9샷Rei",
    avatarColor: "#fb7185",
    monthly: null,
    allTime: null,
  }
];
