// Auto-generated by scripts/scrape.mjs — do not edit manually
// Source: https://www.billizone.com/club/cb_main.php?cb_id=aymania
// Scraped at: 2026-07-18T18:50:01.621Z

export const monthlyLabel = "7월";

import type { Member } from './types'

export const memberData: Member[] = [
  {
    nickname: "9샷레이첼",
    avatarColor: "#f472b6",
    monthly: {
      average: 0.17,
      highrun: 4,
      win: 4,
      draw: 0,
      loss: 11,
      winRate: 27,
      ranks: {
        average: 36,
        highrun: 35,
        winRate: 32,
      },
    },
    allTime: null,
  },
  {
    nickname: "9샷마스웨이",
    avatarColor: "#34d399",
    monthly: {
      average: 0.397,
      highrun: 7,
      win: 8,
      draw: 0,
      loss: 6,
      winRate: 57,
      ranks: {
        average: 24,
        highrun: 10,
        winRate: 13,
      },
    },
    allTime: {
      average: 0.397,
      highrun: 7,
      win: 8,
      draw: 0,
      loss: 6,
      winRate: 57,
      ranks: {
        average: null,
        highrun: null,
        winRate: 84,
      },
    },
  },
  {
    nickname: "9샷애호박",
    avatarColor: "#a78bfa",
    monthly: null,
    allTime: null,
  },
  {
    nickname: "9샷윽고",
    avatarColor: "#60a5fa",
    monthly: null,
    allTime: null,
  },
  {
    nickname: "9샷캐리",
    avatarColor: "#c084fc",
    monthly: {
      average: 0.644,
      highrun: 8,
      win: 13,
      draw: 0,
      loss: 6,
      winRate: 68,
      ranks: {
        average: 5,
        highrun: 4,
        winRate: 8,
      },
    },
    allTime: {
      average: 0.644,
      highrun: 8,
      win: 13,
      draw: 0,
      loss: 6,
      winRate: 68,
      ranks: {
        average: 27,
        highrun: 62,
        winRate: 26,
      },
    },
  },
  {
    nickname: "9샷케인장",
    avatarColor: "#fbbf24",
    monthly: null,
    allTime: {
      average: 0.194,
      highrun: 3,
      win: 21,
      draw: 0,
      loss: 16,
      winRate: 57,
      ranks: {
        average: null,
        highrun: null,
        winRate: 86,
      },
    },
  },
  {
    nickname: "9샷쿤",
    avatarColor: "#2dd4bf",
    monthly: null,
    allTime: null,
  },
  {
    nickname: "9샷Rei",
    avatarColor: "#fb7185",
    monthly: null,
    allTime: null,
  }
];
