// Auto-generated by scripts/scrape.mjs — do not edit manually
// Source: https://www.billizone.com/club/cb_main.php?cb_id=aymania
// Scraped at: 2026-08-14T23:22:20.124Z

export const monthlyLabel = "8월";

import type { Member } from './types'

export const memberData: Member[] = [
  {
    nickname: "9샷레이첼",
    avatarColor: "#f472b6",
    monthly: {
      average: 0.167,
      highrun: 3,
      win: 3,
      draw: 0,
      loss: 8,
      winRate: 27,
      ranks: {
        average: 25,
        highrun: 25,
        winRate: 24,
      },
    },
    allTime: null,
  },
  {
    nickname: "9샷마스웨이",
    avatarColor: "#34d399",
    monthly: {
      average: 0.383,
      highrun: 7,
      win: 8,
      draw: 0,
      loss: 6,
      winRate: 57,
      ranks: {
        average: 21,
        highrun: 6,
        winRate: 5,
      },
    },
    allTime: {
      average: 0.391,
      highrun: 7,
      win: 20,
      draw: 0,
      loss: 15,
      winRate: 57,
      ranks: {
        average: null,
        highrun: null,
        winRate: 87,
      },
    },
  },
  {
    nickname: "9샷애호박",
    avatarColor: "#a78bfa",
    monthly: null,
    allTime: {
      average: 0.435,
      highrun: 6,
      win: 9,
      draw: 0,
      loss: 6,
      winRate: 60,
      ranks: {
        average: null,
        highrun: null,
        winRate: 64,
      },
    },
  },
  {
    nickname: "9샷윽고",
    avatarColor: "#60a5fa",
    monthly: null,
    allTime: null,
  },
  {
    nickname: "9샷캐리",
    avatarColor: "#c084fc",
    monthly: {
      average: 0.552,
      highrun: 7,
      win: 4,
      draw: 0,
      loss: 7,
      winRate: 36,
      ranks: {
        average: 11,
        highrun: 9,
        winRate: 18,
      },
    },
    allTime: {
      average: 0.607,
      highrun: 8,
      win: 24,
      draw: 0,
      loss: 17,
      winRate: 59,
      ranks: {
        average: 42,
        highrun: 74,
        winRate: 76,
      },
    },
  },
  {
    nickname: "9샷케인장",
    avatarColor: "#fbbf24",
    monthly: null,
    allTime: {
      average: 0.194,
      highrun: 3,
      win: 21,
      draw: 0,
      loss: 16,
      winRate: 57,
      ranks: {
        average: null,
        highrun: null,
        winRate: 90,
      },
    },
  },
  {
    nickname: "9샷쿤",
    avatarColor: "#2dd4bf",
    monthly: null,
    allTime: null,
  },
  {
    nickname: "9샷Rei",
    avatarColor: "#fb7185",
    monthly: null,
    allTime: {
      average: 0.44,
      highrun: 6,
      win: 8,
      draw: 0,
      loss: 4,
      winRate: 67,
      ranks: {
        average: null,
        highrun: null,
        winRate: 28,
      },
    },
  }
];
